# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servicos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='servicos.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eservicos.proto\"\x16\n\x05Hello\x12\r\n\x05\x63have\x18\x01 \x01(\t\",\n\x0c\x43reateUpdate\x12\r\n\x05\x63have\x18\x01 \x01(\t\x12\r\n\x05valor\x18\x02 \x01(\t\"\x1b\n\nReadDelete\x12\r\n\x05\x63have\x18\x01 \x01(\t\"\x1d\n\tResultado\x12\x10\n\x08resposta\x18\x01 \x01(\t2\xc5\x01\n\nRequisicao\x12!\n\tConectado\x12\x06.Hello\x1a\n.Resultado\"\x00\x12%\n\x06\x43reate\x12\r.CreateUpdate\x1a\n.Resultado\"\x00\x12!\n\x04Read\x12\x0b.ReadDelete\x1a\n.Resultado\"\x00\x12%\n\x06Update\x12\r.CreateUpdate\x1a\n.Resultado\"\x00\x12#\n\x06\x44\x65lete\x12\x0b.ReadDelete\x1a\n.Resultado\"\x00\x62\x06proto3')
)




_HELLO = _descriptor.Descriptor(
  name='Hello',
  full_name='Hello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='Hello.chave', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=40,
)


_CREATEUPDATE = _descriptor.Descriptor(
  name='CreateUpdate',
  full_name='CreateUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='CreateUpdate.chave', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valor', full_name='CreateUpdate.valor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=86,
)


_READDELETE = _descriptor.Descriptor(
  name='ReadDelete',
  full_name='ReadDelete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='ReadDelete.chave', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=115,
)


_RESULTADO = _descriptor.Descriptor(
  name='Resultado',
  full_name='Resultado',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resposta', full_name='Resultado.resposta', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['Hello'] = _HELLO
DESCRIPTOR.message_types_by_name['CreateUpdate'] = _CREATEUPDATE
DESCRIPTOR.message_types_by_name['ReadDelete'] = _READDELETE
DESCRIPTOR.message_types_by_name['Resultado'] = _RESULTADO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hello = _reflection.GeneratedProtocolMessageType('Hello', (_message.Message,), dict(
  DESCRIPTOR = _HELLO,
  __module__ = 'servicos_pb2'
  # @@protoc_insertion_point(class_scope:Hello)
  ))
_sym_db.RegisterMessage(Hello)

CreateUpdate = _reflection.GeneratedProtocolMessageType('CreateUpdate', (_message.Message,), dict(
  DESCRIPTOR = _CREATEUPDATE,
  __module__ = 'servicos_pb2'
  # @@protoc_insertion_point(class_scope:CreateUpdate)
  ))
_sym_db.RegisterMessage(CreateUpdate)

ReadDelete = _reflection.GeneratedProtocolMessageType('ReadDelete', (_message.Message,), dict(
  DESCRIPTOR = _READDELETE,
  __module__ = 'servicos_pb2'
  # @@protoc_insertion_point(class_scope:ReadDelete)
  ))
_sym_db.RegisterMessage(ReadDelete)

Resultado = _reflection.GeneratedProtocolMessageType('Resultado', (_message.Message,), dict(
  DESCRIPTOR = _RESULTADO,
  __module__ = 'servicos_pb2'
  # @@protoc_insertion_point(class_scope:Resultado)
  ))
_sym_db.RegisterMessage(Resultado)



_REQUISICAO = _descriptor.ServiceDescriptor(
  name='Requisicao',
  full_name='Requisicao',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=149,
  serialized_end=346,
  methods=[
  _descriptor.MethodDescriptor(
    name='Conectado',
    full_name='Requisicao.Conectado',
    index=0,
    containing_service=None,
    input_type=_HELLO,
    output_type=_RESULTADO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='Requisicao.Create',
    index=1,
    containing_service=None,
    input_type=_CREATEUPDATE,
    output_type=_RESULTADO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='Requisicao.Read',
    index=2,
    containing_service=None,
    input_type=_READDELETE,
    output_type=_RESULTADO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='Requisicao.Update',
    index=3,
    containing_service=None,
    input_type=_CREATEUPDATE,
    output_type=_RESULTADO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='Requisicao.Delete',
    index=4,
    containing_service=None,
    input_type=_READDELETE,
    output_type=_RESULTADO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REQUISICAO)

DESCRIPTOR.services_by_name['Requisicao'] = _REQUISICAO

# @@protoc_insertion_point(module_scope)
